version: '3.9'

services:
  
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nl876#
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local